name: responsive
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
